### ISSUE TITLE
Handle filepath and directory better in config

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#277]
We should manually concatenate components with `</>` so it could both work on Windows as well

**Comment by chshersh** [comment]
I tried this approach, but it doesn't work well. For example, roundtrip tests are failing, which means that users will be very surprised by errors in output (e.g. `cli-to-toml` command will be horribly broken). The problem seems to be more difficult than we expected, and the current solution is to have different configs on Windows and Posix with paths specific to that platform. This is what we did for Stan itself to make it run on CI.

I expected Haskell libraries to have standard functions of handling paths seamlessly without worrying about the platform, but they don't work that way at the moment.
