### ISSUE TITLE
Store file map in Analysis

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#76]
This will help to keep per file information that could be used for more detailed reports.
For example, it could contain LoC, extensions per file.

**Comment by chshersh** [comment]
@vrom911 That's a very nice idea! :+1: In addition, instead of `[Observation]` in the `Analysis` type, we can store `Slist Obsevation` in this new `Map` as well and get grouping by `FilePath` for free. Grouping by some different values will require a bit more work, but I think it's not a problem since we can't display extensions per file if we group by category anyway. And we can always convert `Map` to list of pairs, concat second values and regroup.
