### ISSUE TITLE
How to handle Stan errors?

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#80]
For example, missing cabal files, missing hie files?
We need to decide on the architecture for that.

**Comment by chshersh** [comment]
@vrom911 Good point 👍  It probably will be a bit challenging, since:

1. Not everything is error that should stop `stan` execution. For example, missing `.cabal` file is a warning, so in such case we should just print the message and continue.
2. Some errors are local and we may want to have modular errors. So the _missing `.cabal` file_ can happen only at the beginning of stan execution and only inside one command (at the moment), so we can't handle all errors in one place on top-level. When trying to parse  a `Cabal`, we have only two cases at the moment, so having a single global error type may not be always convenient...
